#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  5 16:20:30 2021

@author: fest-men
"""
    ##create a BMI calculation applicatiion  

from pywebio.input import *
from pywebio.output import *


def bmicalculator():
    height=input("please enter the height in cm",type=FLOAT)
    weight=input("please enter the weight in kg",type=FLOAT)
    
    bmi=weight/(height/100)**2
    
    bmi_output=[(16, 'severely underweight'), (18.5, 'underweight' ),
                (25, 'normal'), (30, 'overweight'),(35, 'moderately obese'), 
                (float('inf'), 'severely obese')]  

    for tuple1,tuple2 in bmi_output:
        if bmi<=tuple1:
            put_text('your BMI is :%.1f and the person is :%s'%(bmi,tuple2)) 
            break

                
if __name__=='__main__':
     bmicalculator()
                                                      